server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'microservices'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'admin123'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
application:
  title: Fraud
  version: v1
